name: Flutter CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      # Baixar o código
      - uses: actions/checkout@v3

      # Configurar Java
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      #Configurar Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      #Baixar dependências
      - name: Install dependencies
        run: flutter pub get

      #Analisar código
      - name: Analyze code
        run: flutter analyze

      #Rodar testes
      - name: Run tests
        run: flutter test